[workspace]
members = [
    "server_info_client_rs",
    "server_info_server_rs",
    "server_info_packets",
]

[profile.dev]
opt-level = 0
lto = false

[profile.release]
overflow-checks = true
opt-level = 3
strip = true
debug-assertions = false
lto = true
